version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell
    - revive
    - unconvert
    - unparam
    - nolintlint
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - unparam
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rasulov-emirlan/zenflow-devices-api

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
