services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: zenflow
      POSTGRES_PASSWORD: zenflow
      POSTGRES_DB: zenflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenflow -d zenflow"]
      interval: 2s
      timeout: 3s
      retries: 20

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      DATABASE_URL: postgres://zenflow:zenflow@postgres:5432/zenflow?sslmode=disable
      LOG_LEVEL: info
      APP_ENV: dev
      MIGRATE_MODE: auto
      SEED_ON_BOOT: "true"
      BASIC_AUTH_USERS: "alice:$$2a$$10$$Y10WC4uCFi2qC5f/gts5s.5qYGjkRJM5It.MKhZvAevUnto6fyMgi"
    ports:
      - "8080:8080"
