apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-local
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s

  - name: Tempo
    type: tempo
    uid: tempo-local
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: prometheus-local
        tags:
          - key: service.name
            value: service
        queries:
          - name: "Request rate"
            query: "sum(rate(http_requests_total[1m]))"
          - name: "P95 latency"
            query: "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
      serviceMap:
        datasourceUid: prometheus-local
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        hide: true
